// Code generated by mockery v2.46.3. DO NOT EDIT.

package wssession_mock

import mock "github.com/stretchr/testify/mock"

// MockOnDisconnectFn is an autogenerated mock type for the OnDisconnectFn type
type MockOnDisconnectFn struct {
	mock.Mock
}

type MockOnDisconnectFn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOnDisconnectFn) EXPECT() *MockOnDisconnectFn_Expecter {
	return &MockOnDisconnectFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *MockOnDisconnectFn) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOnDisconnectFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockOnDisconnectFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *MockOnDisconnectFn_Expecter) Execute() *MockOnDisconnectFn_Execute_Call {
	return &MockOnDisconnectFn_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *MockOnDisconnectFn_Execute_Call) Run(run func()) *MockOnDisconnectFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOnDisconnectFn_Execute_Call) Return(_a0 error) *MockOnDisconnectFn_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOnDisconnectFn_Execute_Call) RunAndReturn(run func() error) *MockOnDisconnectFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOnDisconnectFn creates a new instance of MockOnDisconnectFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOnDisconnectFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOnDisconnectFn {
	mock := &MockOnDisconnectFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
