// Code generated by mockery v2.46.3. DO NOT EDIT.

package wssession_mock

import mock "github.com/stretchr/testify/mock"

// MockWebsocketConn is an autogenerated mock type for the WebsocketConn type
type MockWebsocketConn struct {
	mock.Mock
}

type MockWebsocketConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsocketConn) EXPECT() *MockWebsocketConn_Expecter {
	return &MockWebsocketConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockWebsocketConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsocketConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockWebsocketConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockWebsocketConn_Expecter) Close() *MockWebsocketConn_Close_Call {
	return &MockWebsocketConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockWebsocketConn_Close_Call) Run(run func()) *MockWebsocketConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsocketConn_Close_Call) Return(_a0 error) *MockWebsocketConn_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsocketConn_Close_Call) RunAndReturn(run func() error) *MockWebsocketConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMessage provides a mock function with given fields:
func (_m *MockWebsocketConn) ReadMessage() (int, []byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadMessage")
	}

	var r0 int
	var r1 []byte
	var r2 error
	if rf, ok := ret.Get(0).(func() (int, []byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func() []byte); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockWebsocketConn_ReadMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMessage'
type MockWebsocketConn_ReadMessage_Call struct {
	*mock.Call
}

// ReadMessage is a helper method to define mock.On call
func (_e *MockWebsocketConn_Expecter) ReadMessage() *MockWebsocketConn_ReadMessage_Call {
	return &MockWebsocketConn_ReadMessage_Call{Call: _e.mock.On("ReadMessage")}
}

func (_c *MockWebsocketConn_ReadMessage_Call) Run(run func()) *MockWebsocketConn_ReadMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsocketConn_ReadMessage_Call) Return(messageType int, p []byte, err error) *MockWebsocketConn_ReadMessage_Call {
	_c.Call.Return(messageType, p, err)
	return _c
}

func (_c *MockWebsocketConn_ReadMessage_Call) RunAndReturn(run func() (int, []byte, error)) *MockWebsocketConn_ReadMessage_Call {
	_c.Call.Return(run)
	return _c
}

// WriteJSON provides a mock function with given fields: msgType
func (_m *MockWebsocketConn) WriteJSON(msgType interface{}) error {
	ret := _m.Called(msgType)

	if len(ret) == 0 {
		panic("no return value specified for WriteJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(msgType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsocketConn_WriteJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteJSON'
type MockWebsocketConn_WriteJSON_Call struct {
	*mock.Call
}

// WriteJSON is a helper method to define mock.On call
//   - msgType interface{}
func (_e *MockWebsocketConn_Expecter) WriteJSON(msgType interface{}) *MockWebsocketConn_WriteJSON_Call {
	return &MockWebsocketConn_WriteJSON_Call{Call: _e.mock.On("WriteJSON", msgType)}
}

func (_c *MockWebsocketConn_WriteJSON_Call) Run(run func(msgType interface{})) *MockWebsocketConn_WriteJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockWebsocketConn_WriteJSON_Call) Return(_a0 error) *MockWebsocketConn_WriteJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsocketConn_WriteJSON_Call) RunAndReturn(run func(interface{}) error) *MockWebsocketConn_WriteJSON_Call {
	_c.Call.Return(run)
	return _c
}

// WriteMessage provides a mock function with given fields: messageType, data
func (_m *MockWebsocketConn) WriteMessage(messageType int, data []byte) error {
	ret := _m.Called(messageType, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []byte) error); ok {
		r0 = rf(messageType, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWebsocketConn_WriteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessage'
type MockWebsocketConn_WriteMessage_Call struct {
	*mock.Call
}

// WriteMessage is a helper method to define mock.On call
//   - messageType int
//   - data []byte
func (_e *MockWebsocketConn_Expecter) WriteMessage(messageType interface{}, data interface{}) *MockWebsocketConn_WriteMessage_Call {
	return &MockWebsocketConn_WriteMessage_Call{Call: _e.mock.On("WriteMessage", messageType, data)}
}

func (_c *MockWebsocketConn_WriteMessage_Call) Run(run func(messageType int, data []byte)) *MockWebsocketConn_WriteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].([]byte))
	})
	return _c
}

func (_c *MockWebsocketConn_WriteMessage_Call) Return(_a0 error) *MockWebsocketConn_WriteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWebsocketConn_WriteMessage_Call) RunAndReturn(run func(int, []byte) error) *MockWebsocketConn_WriteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWebsocketConn creates a new instance of MockWebsocketConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsocketConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsocketConn {
	mock := &MockWebsocketConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
