// Code generated by mockery v2.46.3. DO NOT EDIT.

package wssession_mock

import mock "github.com/stretchr/testify/mock"

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// SendJSON provides a mock function with given fields: msgType, j
func (_m *MockWriter) SendJSON(msgType string, j any) error {
	ret := _m.Called(msgType, j)

	if len(ret) == 0 {
		panic("no return value specified for SendJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(msgType, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_SendJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendJSON'
type MockWriter_SendJSON_Call struct {
	*mock.Call
}

// SendJSON is a helper method to define mock.On call
//   - msgType string
//   - j any
func (_e *MockWriter_Expecter) SendJSON(msgType interface{}, j interface{}) *MockWriter_SendJSON_Call {
	return &MockWriter_SendJSON_Call{Call: _e.mock.On("SendJSON", msgType, j)}
}

func (_c *MockWriter_SendJSON_Call) Run(run func(msgType string, j any)) *MockWriter_SendJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *MockWriter_SendJSON_Call) Return(_a0 error) *MockWriter_SendJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_SendJSON_Call) RunAndReturn(run func(string, any) error) *MockWriter_SendJSON_Call {
	_c.Call.Return(run)
	return _c
}

// SendStr provides a mock function with given fields: msgType, msg
func (_m *MockWriter) SendStr(msgType string, msg string) error {
	ret := _m.Called(msgType, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendStr")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(msgType, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_SendStr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStr'
type MockWriter_SendStr_Call struct {
	*mock.Call
}

// SendStr is a helper method to define mock.On call
//   - msgType string
//   - msg string
func (_e *MockWriter_Expecter) SendStr(msgType interface{}, msg interface{}) *MockWriter_SendStr_Call {
	return &MockWriter_SendStr_Call{Call: _e.mock.On("SendStr", msgType, msg)}
}

func (_c *MockWriter_SendStr_Call) Run(run func(msgType string, msg string)) *MockWriter_SendStr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockWriter_SendStr_Call) Return(_a0 error) *MockWriter_SendStr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_SendStr_Call) RunAndReturn(run func(string, string) error) *MockWriter_SendStr_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
